-- =====================================================================
-- MIGRASI SUPABASE: ALUR PEMILIHAN EKSEKUTOR & TUGAS (TASKS) PENGADUAN
-- Fitur Pengaduan Aplikasi SIMPEG (Flutter + Supabase)
-- =====================================================================

-- 1. Tambah kolom `executor_id` pada tabel `pengaduan_pegawai` (jika belum ada)
-- Column storing foreign key to `pegawai(id)` for selected executor
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'pengaduan_pegawai'
          AND column_name = 'executor_id'
    ) THEN
        ALTER TABLE public.pengaduan_pegawai
        ADD COLUMN executor_id UUID REFERENCES public.pegawai(id) ON DELETE SET NULL;
    END IF;
END $$;

-- Index pada executor_id agar query cepat
CREATE INDEX IF NOT EXISTS idx_pengaduan_pegawai_executor_id 
ON public.pengaduan_pegawai(executor_id);


-- 2. Buat tabel `tasks` (Tugas Eksekusi Pengaduan) jika belum ada
CREATE TABLE IF NOT EXISTS public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pengaduan_id BIGINT REFERENCES public.pengaduan_pegawai(id) ON DELETE CASCADE,
    assigned_to UUID REFERENCES public.pegawai(id) ON DELETE SET NULL,
    assigned_by UUID REFERENCES public.pegawai(id) ON DELETE SET NULL,
    assigned_by_name TEXT,
    title TEXT NOT NULL,
    category TEXT,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'Menunggu', -- Options: 'Menunggu', 'Diproses', 'Selesai', 'Dibatalkan'
    notes TEXT,
    proof_files JSONB DEFAULT '[]'::jsonb,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexing pada tabel tasks
CREATE INDEX IF NOT EXISTS idx_tasks_assigned_to ON public.tasks(assigned_to);
CREATE INDEX IF NOT EXISTS idx_tasks_pengaduan_id ON public.tasks(pengaduan_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON public.tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_is_active ON public.tasks(is_active);


-- 3. Tambah kolom `task_id` pada tabel `notifikasi` (jika belum ada)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'notifikasi'
          AND column_name = 'task_id'
    ) THEN
        ALTER TABLE public.notifikasi
        ADD COLUMN task_id BIGINT REFERENCES public.tasks(id) ON DELETE CASCADE;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_notifikasi_task_id 
ON public.notifikasi(task_id);


-- 4. ATUR RLS (ROW LEVEL SECURITY) UNTUK TABEL `tasks`
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- Dynamic Policy: Drop existing policies before creating to avoid duplicate policy errors
DROP POLICY IF EXISTS "KSPI can insert and update tasks" ON public.tasks;
DROP POLICY IF EXISTS "Executors can view their assigned tasks" ON public.tasks;
DROP POLICY IF EXISTS "Executors can update their assigned tasks" ON public.tasks;
DROP POLICY IF EXISTS "Relevant roles can view tasks" ON public.tasks;

-- Policy 1: KSPI (role = 'kspi') dapat membuat & memperbarui task apapun
CREATE POLICY "KSPI can insert and update tasks"
ON public.tasks
FOR ALL
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.pegawai
        WHERE pegawai.id = auth.uid()
          AND pegawai.role = 'kspi'
    )
);

-- Policy 2: Eksekutor dapat melihat task yang ditugaskan kepadanya (assigned_to = auth.uid())
CREATE POLICY "Executors can view their assigned tasks"
ON public.tasks
FOR SELECT
TO authenticated
USING (
    assigned_to = auth.uid()
    OR EXISTS (
        SELECT 1 FROM public.pegawai
        WHERE pegawai.id = auth.uid()
          AND pegawai.role IN ('kspi', 'dirut', 'direktur', 'sdm')
    )
);

-- Policy 3: Eksekutor hanya bisa mengubah/memperbarui task miliknya sendiri
CREATE POLICY "Executors can update their assigned tasks"
ON public.tasks
FOR UPDATE
TO authenticated
USING (
    assigned_to = auth.uid()
)
WITH CHECK (
    assigned_to = auth.uid()
);


-- 5. ATUR RLS UNTUK `pengaduan_pegawai` (Pastikan KSPI & Eksekutor bisa update)
-- Drop existing policies if needed or ensure update policy exists
DROP POLICY IF EXISTS "KSPI can update executor_id" ON public.pengaduan_pegawai;
CREATE POLICY "KSPI can update executor_id"
ON public.pengaduan_pegawai
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.pegawai
        WHERE pegawai.id = auth.uid()
          AND pegawai.role = 'kspi'
    )
    OR executor_id = auth.uid()
);

-- Notification realtime broadcast channel setting (Opsional)
COMMENT ON TABLE public.tasks IS 'Tabel penugasan eksekutor pengaduan SIMPEG';
